version: '2'
services:
  notebook: 
    build:
      context: ../jupyter/
      dockerfile: Dockerfile
    image: ccdcoe/sdm-jupyter-notebook:latest
    volumes:
      - ../../:/home/jovyan/books
      - ${HOME}/data:/home/jovyan/data
    ports:
      - 8888:8888
  lab:
    build:
      context: ../jupyter/jupyterLab/
      dockerfile: ./Dockerfile
    image: ccdcoe/sdm-jupyter-lab:latest
    volumes:
      - ../../:/home/jovyan/books
      - ${HOME}/data:/home/jovyan/data
    ports:
      - 8889:8888
    depends_on:
      - notebook
  rstudio:
    image: rocker/rstudio
    ports: 
      - 8787:8787
    volumes:
      - ../../:/home/rstudio/code
      - ${HOME}/data:/home/rstudio/data
      - ${HOME}/R:/home/rstudio/R
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
    depends_on:
      - notebook
      - lab
  influx:
    image: influxdb
    depends_on:
      - notebook
      - lab
  zk:
    image: elevy/zookeeper:latest
    depends_on:
      - notebook
      - lab
    environment:
      MYID: 1
      SERVERS: zk
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zk
      - notebook
      - lab
    environment:
      KAFKA_LOG_DIRS: /kafka
      KAFKA_BROKER_ID: 1
      #KAFKA_ADVERTISED_HOST_NAME: 192.168.10.1
      #KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_RETENTION_HOURS: "72"
      KAFKA_LOG_RETENTION_BYTES: "-1"
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_ZOOKEEPER_CONNECT:  zk:2181,
  mariadb:
    image: mariadb
    depends_on:
      - notebook
      - lab
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'stronk'
